In [4]:
import keras.models
import warnings 
import numpy as np
warnings.simplefilter('ignore')
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from numpy import array
import pandas as pd

df=pd.read_csv('total_cases.csv')
df=df[["date","India"]]

# split a univariate sequence into samples
def split_sequence(sequence, n_steps_in, n_steps_out):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps_in
        out_end_ix = end_ix + n_steps_out
        # check if we are beyond the sequence
        if out_end_ix > len(sequence):
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:out_end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y) 


Using TensorFlow backend.


In [5]:
# define input sequence
# choose a number of time steps
n_steps_in, n_steps_out = 3,2

# split into samples
X, y = split_sequence(df["India"], n_steps_in, n_steps_out)

# summarize the data
for i in range(len(X)):
	print(X[i], y[i]) 

#reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 0]
[0 0 0] [0 1]
[0 0 0] [1 1]
[0 0 1] [1 1]
[0 1 1] [1 2]
[1 1 1] [2 2]
[1 1 2] [2 3]
[1 2 2] [3 3]
[2 2 3] [3 3]
[2 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 3]
[3 3 3] [3 5]
[3 3 3] [5 6]
[3 3 5] [ 6 28]
[3 5 6] [28 29]
[ 5  6 28] [29 31]
[ 6 28 29] [31 34]
[28 29 31] [34 43]
[29 31 34] [43 44]
[31 34 43] [44 50]
[34 43 44] [50 73]


In [7]:
#Using optimal hyper-parameters found by experimenting with present data 
# model = Sequential()
# model.add(LSTM(100, activation='relu', return_sequences=True, input_shape=(n_steps_in, n_features)))
# model.add(LSTM(100, activation='relu'))
# model.add(Dense(n_steps_out))
# model.compile(optimizer='adam', loss='mse')

#fit model
# model.fit(X, y, epochs=50, verbose=0) #epochs = 50 by hit and trial and observing with present data 

error_arr = []
predict = []

for i in range(len(X)):
    x_input = X[i]
    x_input = x_input.reshape((1, n_steps_in, n_features))
    predictions = model.predict(x_input, verbose=0)
    predict.append(predictions)
    print(predictions)
    error = (predictions - y[i])/ y[i]
    error = ((error*100).mean())
    error_arr.append(error)

[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.03721095 0.09270811]]
[[0.37118277 0.3778427 ]]
[[0.8289326 0.8117247]]
[[1.4825352 1.5179688]]
[[1.6679485 1.6838547]]
[[2.1360862 2.192936 ]]
[[3.3593414 3.568811 ]]
[[3.9698381 4.27342  ]]
[[5.171572  5.7930584]]
[[5.171572  5.7930584]]
[[5.171572  5.7930584]]
[[5.171572  5.7930584]]
[[5.17

In [8]:
error = abs(np.mean(error_arr[100:]))
print(error)

3.20331884556505


In [39]:
actual = df["India"]
print(actual[112:])

predicted = np.array(predict)
for i in range(110,143):
    print(predicted[i][0][1])

112     18600
113     19984
114     21393
115     23077
116     24506
117     26496
118     27892
119     29435
120     31332
121     33050
122     35043
123     37336
124     39980
125     42533
126     46433
127     49391
128     52952
129     56342
130     59662
131     62939
132     67152
133     70756
134     74281
135     78003
136     81970
137     85940
138     90927
139     96169
140    101139
141    106750
142    112359
143    118447
144    125101
145    131868
146    138845
Name: India, dtype: int64
20254.95
21973.654
23615.508
25355.604
27183.781
29149.168
31128.164
33125.203
34984.527
37047.09
39257.016
41581.684
44265.195
47244.91
50656.266
54464.414
58608.227
62546.89
66680.73
70687.37
74850.34
79310.164
83911.49
88222.22
92646.07
97285.7
102275.82
107820.914
113922.69
120160.72
126578.69
133415.31
140612.53
